<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>no checking</name>
  <uuid>87c61a99-0c86-4f7a-a92b-ed72ab1e141c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	there is no Account in the accountses of the borrower 
	where the type of this Account is "checking" ,
then
	set the checkingstatus of decision to "no_checking" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
