<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>no savings</name>
  <uuid>f953d4a4-95b6-4b53-8530-26b73fd45058</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	there is no Account in the accountses of the borrower of Loan 
	where the type of this Account is "savings",
then
	set the existingsavings of decision to "unknown" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
