<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>others on loan</name>
  <uuid>2f3eec6f-55cb-4754-98e8-85693517eebc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the co-borrower of Loan is null
then
	set the othersonloan of decision to "none" ;
else
	set the othersonloan of decision to the role of the co-borrower of Loan ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
