<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>telephone</name>
  <uuid>56e5cb07-0453-473b-9bda-1801fdbe3b75</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the phone number of the borrower of Loan is null
then
	set the telephone of decision to "none" ;
else
	set the telephone of decision to "yes" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
