<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b23ccc9e-9b32-4fea-afc6-619359bc5324</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Risk where
		the combined value is low , 
		the loan amount risk is 'Assess loan amount risk decision',
		the relationship risk component is  'Assess bank relationship risk decision';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
