<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a1c770db-a2f5-470b-a7e7-8d729ac7ee90</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to medium ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
